# Generated by Django 5.2.9 on 2026-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
