# Generated by Django 5.2.9 on 2026-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
