# Generated by Django 5.2.9 on 2026-01-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_property_description_en_property_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ru',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
